Updated README usage information
cyberark/conjur-sdk-java pull request #61
Opened 2021-09-13 14:17 UTC by telday

### What does this PR do?
Updated ReadMe to include more detailed information about client setup/configuration.

### Checklists

#### Change log
- [ ] The CHANGELOG has been updated, or
- [x] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [x] The changes in this PR do not require tests

#### Documentation
- [x] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [ ] This PR does not require updating any documentation

2021-09-20 13:28 UTC, john-odonnell commented on README.md
> +4a. For Intellij, Follow the steps outlined [here](https://www.jetbrains.com/help/idea/library.html)
4a, b and c are a single, unbroken line in the rendered MD: https://github.com/cyberark/conjur-sdk-java/tree/update-usage-documentation#using-the-jarfile

Also, the code blocks below are rendered as one continuous block, including backticks.

2021-09-20 13:35 UTC, john-odonnell requested changes
Looks good! I've made a comment (above, accidentally outside of the review scope).

2021-09-20 17:51 UTC, john-odonnell approved these changes
LGTM 👍

2021-09-20 18:08 UTC, merged

2021-09-20 19:52 UTC, alexkalish commented
Thanks, @telday!!  Looks great.

2021-09-23 06:20 UTC, sigalsax commented on README.md
> +client.setUsername("username");
came across this PR and just popping in here for a second :)
Is this sustainable if we keep adding new ways to login to the client? 

What about items like account, cert_file, and url. Can they be set in this way as well?