Bump version to 4.1.0
cyberark/conjur-sdk-java pull request #72
Opened 2022-04-01 13:03 UTC by szh

2022-04-01 13:43 UTC, gl-johnson reviewed
LGTM - although I am not sure if the release process for this repo necessitates updating pom.mustache to reflect the new version, i.e. 
`<version>4.0.0-SNAPSHOT</version>` ---> `<version>4.1.0-SNAPSHOT</version>`

Pinging @john-odonnell or @telday

2022-04-01 17:15 UTC, john-odonnell commented
Yeah, fairly certain we should update `pom.mustache` version before releasing.
The `bin/deploy-release` script will uses `mvn version:set -DnewVersion=${TAG}`,
which should update `client/pom.xml` to the build tag, but our template would be out of sync if it hadn't been updated.

@telday wrote all the release tooling here - he'd know for certain.

Whatever the outcome, we should definitely make note in the Contributing doc.

2022-04-01 17:25 UTC, telday commented
@john-odonnell Is correct here, the release script does run a `mvn version:set` before it releasees which will set the correct version based on the tag you are releasing for. However the next time the `pom.xml` is regenerated it will have the old version. I actually don't think this would cause any issues, but it may be confusing if it is not kept up to date.

2022-04-01 20:25 UTC, john-odonnell requested changes
Need one small fix in the Changelog links. LGTM otherwise!

2022-04-01 20:25 UTC, john-odonnell commented on CHANGELOG.md
> +[Unreleased]: https://github.com/cyberark/conjur-sdk-java/compare/v4.0.0...HEAD
```suggestion
[Unreleased]: https://github.com/cyberark/conjur-sdk-java/compare/v4.1.0...HEAD
```

2022-04-04 14:58 UTC, john-odonnell approved these changes
LGTM 👍

2022-04-04 15:00 UTC, merged